# Generated by Django 5.1.4 on 2024-12-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0009_alter_project_status_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complited', 'Выполнено'), ('В разработке', 'In Development'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низкий'), ('Average', 'Cредний'), ('Высокий', 'High'), ('Не указан', 'Not specified')], default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Complited', 'Выполнено'), ('В разработке', 'In Development'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
    ]
