# Generated by Django 5.1.4 on 2024-12-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0018_alter_project_participants_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='p_role', to='scp.role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Complited'), ('In Development', 'В разработке'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Low'), ('Average', 'Cредний'), ('Высокий', 'High'), ('Not specified', 'Не указан')], default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Complited'), ('In Development', 'В разработке'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
    ]
