# Generated by Django 5.1.4 on 2024-12-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0024_remove_profile_role_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Администратор', 'Administrator'), ('Исполнитель', 'Executor')], default='Executor', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complited', 'Выполнено'), ('В разработке', 'In Development'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Low'), ('Cредний', 'Average'), ('High', 'Высокий'), ('Not specified', 'Не указан')], default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Complited', 'Выполнено'), ('В разработке', 'In Development'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
    ]
