# Generated by Django 5.1.4 on 2025-01-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0035_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Banned', 'Заблокирован'), ('Not banned', 'Не заблокирован')], default='Not banned', max_length=50),
        ),
    ]
