# Generated by Django 5.1.4 on 2025-01-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0040_alter_profile_status_alter_project_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Заблокирован', 'Banned'), ('Не заблокирован', 'NotBanned')], default='NotBanned', max_length=50),
        ),
    ]
