# Generated by Django 5.1.4 on 2025-01-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0041_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Администратор', 'Administrator'), ('Исполнитель', 'Executor')], default='Executor', max_length=50),
        ),
    ]
