# Generated by Django 5.1.4 on 2025-01-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/user_file/'),
        ),
    ]
