# Generated by Django 5.1.4 on 2025-01-26 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0004_alter_project_complexity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='statia_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Код'),
        ),
    ]
