# Generated by Django 5.1.4 on 2024-12-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0005_remove_language_name_remove_project_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низкий'), ('Cредний', 'Average'), ('High', 'Высокий'), ('Не указан', 'Not specified')], default='Not specified', max_length=50),
        ),
    ]
