# Generated by Django 5.1.4 on 2024-12-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Complited'), ('В разработке', 'In Development'), ('Ожидает', 'Waiting')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низкий'), ('Average', 'Cредний'), ('High', 'Высокий'), ('Not specified', 'Не указан')], default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Complited'), ('В разработке', 'In Development'), ('Ожидает', 'Waiting')], default='Waiting', max_length=50),
        ),
    ]
