# Generated by Django 5.1.4 on 2025-01-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0007_alter_post_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.TextField(default='Контакты не указаны'),
        ),
    ]
