# Generated by Django 5.1.4 on 2025-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0010_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='./static/scp/image/no_avatar.png', null=True, upload_to='./profile_avatars/'),
        ),
    ]
