# Generated by Django 5.1.4 on 2024-12-29 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0011_alter_project_status_alter_task_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='p_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Complited'), ('В разработке', 'In Development'), ('Ожидает', 'Waiting')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низкий'), ('Average', 'Cредний'), ('High', 'Высокий'), ('Не указан', 'Not specified')], default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Complited'), ('В разработке', 'In Development'), ('Ожидает', 'Waiting')], default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(related_name='p_role', to='scp.role'),
        ),
    ]
