# Generated by Django 5.1.4 on 2024-12-29 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0012_role_alter_project_participants_alter_project_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Complited'), ('In Development', 'В разработке'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низкий'), ('Cредний', 'Average'), ('High', 'Высокий'), ('Not specified', 'Не указан')], default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Complited'), ('In Development', 'В разработке'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
