# Generated by Django 5.1.4 on 2025-02-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0012_profile_github_url_profile_telegram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
    ]
