# Generated by Django 5.1.4 on 2024-12-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0023_profile_status_alter_project_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complited', 'Выполнено'), ('In Development', 'В разработке'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низкий'), ('Average', 'Cредний'), ('High', 'Высокий'), ('Not specified', 'Не указан')], default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Complited', 'Выполнено'), ('In Development', 'В разработке'), ('Waiting', 'Ожидает')], default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrator', 'Администратор'), ('Executor', 'Исполнитель')], default='Executor', max_length=50),
        ),
    ]
