# Generated by Django 5.1.4 on 2025-01-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0031_alter_project_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='./profile_avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrator', 'Администратор'), ('Executor', 'Исполнитель')], default='Executor', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Заблокирован', 'Baned'), ('Не заблокирован', 'Not baned')], default='Not baned', max_length=50),
        ),
    ]
