# Generated by Django 5.1.4 on 2025-01-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0032_alter_profile_avatar_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Заблокирован', 'Banned'), ('Не заблокирован', 'Not baned')], default='Not baned', max_length=50),
        ),
    ]
