# Generated by Django 5.1.4 on 2025-01-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0042_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.CharField(choices=[('Онлайн', 'Online'), ('Офлайн', 'Оffline'), ('Деактивирована', 'Deactivated')], default='Online', max_length=50),
        ),
    ]
