# Generated by Django 5.1.4 on 2025-01-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0044_alter_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.BooleanField(default=False),
        ),
    ]
