# Generated by Django 5.1.4 on 2025-01-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0045_alter_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Заблокирован', 'Banned'), ('Не заблокирован', 'NotBanned')], default='Не заблокирован', max_length=50),
        ),
    ]
