# Generated by Django 5.1.4 on 2025-01-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0046_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Администратор', 'Administrator'), ('Исполнитель', 'Executor')], default='Исполнитель', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Заблокирован', 'Заблокирован'), ('Не заблокирован', 'Не заблокирован')], default='Не заблокирован', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('C', 'С'), ('C++', 'С++'), ('C#', 'С#'), ('Go', 'Go'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Kotlin', 'Kotlin'), ('PHP', 'PHP'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Rust', 'Rust'), ('TypeScript', 'TypeScript'), ('Swift', 'Swift'), ('Shell', 'Shell'), ('Perl', 'Perl'), ('Lua', 'Lua'), ('SQL', 'SQL'), ('Assembly', 'Ассемблер'), ('Not specified', 'Не указан')], default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('В разработке', 'В разработке'), ('Ожидает', 'Ожидает')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Cредний', 'Cредний'), ('Высокий', 'Высокий'), ('Не указан', 'Не указан')], default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('В разработке', 'В разработке'), ('Ожидает', 'Ожидает')], default='Waiting', max_length=50),
        ),
    ]
