# Generated by Django 5.1.4 on 2025-01-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0048_alter_project_end_date_alter_project_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('C', 'С'), ('C++', 'С++'), ('C#', 'С#'), ('Go', 'Go'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Kotlin', 'Kotlin'), ('PHP', 'PHP'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Rust', 'Rust'), ('TypeScript', 'TypeScript'), ('Swift', 'Swift'), ('Shell', 'Shell'), ('Perl', 'Perl'), ('Lua', 'Lua'), ('SQL', 'SQL'), ('Assembly', 'Ассемблер'), ('Not specified', 'Не указан')], default='Не указан', max_length=50, verbose_name='Язык программирования'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('В разработке', 'В разработке'), ('Ожидает', 'Ожидает')], default='Ожидает', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Cредний', 'Cредний'), ('Высокий', 'Высокий'), ('Не указан', 'Не указан')], default='Не указан', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('В разработке', 'В разработке'), ('Ожидает', 'Ожидает')], default='Ожидает', max_length=50, verbose_name='Cтатус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название задачи'),
        ),
    ]
