# Generated by Django 5.1.4 on 2025-01-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0049_alter_project_language_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Cредний', 'Cредний'), ('Высокий', 'Высокий'), ('Не указан', 'Не указан')], default='Не указан', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
