# Generated by Django 5.1.4 on 2025-01-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0050_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('Низкий', 'Низкий'), ('Cредний', 'Cредний'), ('Высокий', 'Высокий'), ('Не указан', 'Не указан')], default='Не указан', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
