# Generated by Django 5.1.4 on 2025-01-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0052_alter_task_assignee_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
