# Generated by Django 5.1.4 on 2025-01-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0054_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
